services:
  - type: web
    name: fakeit
    env: static
    staticPublishPath: dist/app-fakeit
    buildCommand: npm install && npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
